sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - binutils-dev
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libdw-dev
    - libiberty-dev

script:
- ./travis_coverage.sh

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: formatting
      rust: nightly
      script: rustup component add rustfmt-preview && cargo fmt --all -- --check

cache:
  - cargo
  - ccache
  - directories:
    - $HOME/.local/bin
