language: rust

rust:
  - stable
  - beta
  - nightly

script:
- cargo build
- cargo test

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: formatting
      rust: nightly
      script: rustup component add rustfmt-preview && cargo fmt --all -- --check

cache: cargo
