[package]
name = "fp-succinct-trees-1"
version = "0.1.0"
authors = ["David Mehren <dmehren1@gmail.com>"]

[dependencies]
bv = "0.7"
bio = "0.19.0"
id_tree = "1.3.0"
failure = "0.1.1"
serde = "1.0.64"
serde_derive = "1.0.64"
bincode = "1.0.0"